# Generated by Django 5.0.1 on 2024-02-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('contenido', models.TextField()),
                ('id_publicacion', models.IntegerField()),
                ('id_usuario_comentario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('contenido', models.TextField()),
                ('estatus', models.CharField(choices=[('enviado', 'Enviado'), ('recibido', 'Recibido'), ('leido', 'Leído')], max_length=10)),
                ('id_usuario_orig', models.IntegerField()),
                ('id_usuario_dest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('id_usuario', models.IntegerField()),
                ('tipo', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.TextField()),
            ],
        ),
    ]
